export const DEFAULT_SHORTCUTS: Record<string, string> = {
  newFile: 'Ctrl+N',
  openFile: 'Ctrl+O',
  saveFile: 'Ctrl+S',
  saveAs: 'Ctrl+Shift+S',
  exit: 'Alt+F4',
  undo: 'Ctrl+Z',
  redo: 'Ctrl+Y',
  copy: 'Ctrl+C',
  cut: 'Ctrl+X',
  paste: 'Ctrl+V',
  selectAll: 'Ctrl+A',
  find: 'Ctrl+F',
  replace: 'Ctrl+H',
  toggleExplorer: 'Ctrl+Shift+E',
  toggleVcs: 'Ctrl+Shift+G',
  toggleSidebar: 'Ctrl+B',
  toggleConsole: 'Ctrl+`',
  toggleFullscreen: 'F11',
  zoomIn: 'Ctrl+=',
  zoomOut: 'Ctrl+-',
  resetZoom: 'Ctrl+0',
  goToDefinition: 'F12',
  goToDeclaration: 'Ctrl+F12',
  goToImplementation: 'Ctrl+Shift+F12',
  goBack: 'Alt+Left',
  goForward: 'Alt+Right',
  formatDocument: 'Shift+Alt+F',
  toggleLineComment: 'Ctrl+/',
  toggleBlockComment: 'Shift+Alt+A',
  triggerSuggest: 'Ctrl+Space',
  quickFix: 'Ctrl+.',
  renameSymbol: 'F2',
  extractFunction: 'Ctrl+Shift+R',
  extractVariable: 'Ctrl+Shift+V',
  inlineVariable: 'Ctrl+Shift+L',
  compile: 'Ctrl+Shift+B',
  rebuild: 'Ctrl+Alt+R',
  clean: 'Ctrl+Shift+C',
  run: 'F5',
  debug: 'Ctrl+F5',
  stop: 'Shift+F5',
  settings: 'Ctrl+,',
  commit: 'Ctrl+K',
  push: 'Ctrl+Shift+K',
  pull: 'Ctrl+Shift+P',
  newWindow: 'Ctrl+Shift+N',
  closeTab: 'Ctrl+W',
  closeWindow: 'Ctrl+Shift+W',
  nextTab: 'Ctrl+Tab',
  prevTab: 'Ctrl+Shift+Tab',
  minimize: 'Ctrl+M',
  documentation: 'F1',
  keyboardShortcuts: 'Ctrl+K Ctrl+S',
  explorerNewFile: 'Ctrl+Alt+N',
  explorerNewFolder: 'Ctrl+Alt+Shift+N',
  explorerDelete: 'Delete'
};
export const MENU_SHORTCUT_COMMANDS: Record<string, string> = {
  'new-file': 'newFile',
  'open-file': 'openFile',
  'save-file': 'saveFile',
  'save-as': 'saveAs',
  exit: 'exit',
  undo: 'undo',
  redo: 'redo',
  cut: 'cut',
  copy: 'copy',
  paste: 'paste',
  find: 'find',
  replace: 'replace',
  'toggle-explorer': 'toggleExplorer',
  'toggle-vcs': 'toggleVcs',
  'toggle-console': 'toggleConsole',
  'zoom-in': 'zoomIn',
  'zoom-out': 'zoomOut',
  'reset-zoom': 'resetZoom',
  'go-to-definition': 'goToDefinition',
  'go-to-declaration': 'goToDeclaration',
  'go-to-implementation': 'goToImplementation',
  'go-back': 'goBack',
  'go-forward': 'goForward',
  format: 'formatDocument',
  'comment-line': 'toggleLineComment',
  'comment-block': 'toggleBlockComment',
  intellisense: 'triggerSuggest',
  'quick-fix': 'quickFix',
  'rename-symbol': 'renameSymbol',
  'extract-function': 'extractFunction',
  'extract-variable': 'extractVariable',
  'inline-variable': 'inlineVariable',
  'build-project': 'compile',
  'rebuild-project': 'rebuild',
  'clean-project': 'clean',
  'run-project': 'run',
  'debug-project': 'debug',
  'stop-project': 'stop',
  settings: 'settings',
  preferences: 'settings',
  keybindings: 'keyboardShortcuts',
  commit: 'commit',
  push: 'push',
  pull: 'pull',
  'new-window': 'newWindow',
  'close-window': 'closeWindow',
  minimize: 'minimize',
  fullscreen: 'toggleFullscreen',
  documentation: 'documentation',
  'keyboard-shortcuts': 'keyboardShortcuts'
};
export const SHORTCUTS_ALLOWED_IN_INPUT = new Set(['saveFile', 'saveAs', 'newFile', 'openFile', 'compile', 'rebuild', 'run', 'debug', 'stop', 'toggleConsole', 'toggleSidebar', 'toggleExplorer', 'toggleVcs', 'toggleFullscreen', 'settings', 'keyboardShortcuts', 'commit', 'push', 'pull', 'closeWindow', 'closeTab', 'nextTab', 'prevTab', 'exit', 'zoomIn', 'zoomOut', 'resetZoom', 'newWindow', 'minimize', 'documentation', 'explorerNewFile', 'explorerNewFolder']);
export function getShortcutLabel(shortcuts: Record<string, string>, commandId: string | undefined): string | undefined {
  if (!commandId) return undefined;
  const value = shortcuts[commandId];
  return value || undefined;
}